In [1]:
import pandas as pd

In [3]:
NCHS = pd.read_csv('Data/NCHS_-_Drug_Poisoning_Mortality_by_State__United_States.csv')

# USA Per Capita Overdose Rate by Year

Age-adjusted death rates (deaths per 100,000 U.S. standard population for 2000) are calculated using the direct method

In [31]:
NCHS.loc[(NCHS['State'] == 'United States') 
         & (NCHS['Age Group'] == 'All Ages') 
         & (NCHS['Sex'] == 'Both Sexes')
        & (NCHS['Race and Hispanic Origin'] == 'All Races-All Origins')][
    ['Year','US Age-adjusted Rate']].set_index('Year')

      US Age-adjusted Rate
Year
1999                6.0570
2000                6.1749
2001                6.7922
2002                8.1957
2003                8.8765
2004                9.3831
2005               10.0699
2006               11.4883
2007               11.8775
2008               11.8947
2009               11.9388
2010               12.2966
2011               13.1852
2012               13.1422
2013               13.8005
2014               14.6831
2015               16.2923
2016               19.7851

In [43]:
NCHS.loc[(NCHS['State'] == 'United States') 
         & (NCHS['Age Group'] == 'All Ages') 
         & (NCHS['Sex'] == 'Both Sexes')
        & (NCHS['Race and Hispanic Origin'] == 'All Races-All Origins')][
    ['Year','Deaths', 'Population']].set_index('Year')

      Deaths  Population
Year
1999   16849   279040238
2000   17415   281421906
2001   19394   284968955
2002   23518   287625193
2003   25785   290107933
2004   27424   292805298
2005   29813   295516599
2006   34425   298379912
2007   36010   301231207
2008   36450   304093966
2009   37004   306771529
2010   38329   308745538
2011   41340   311591917
2012   41502   313914040
2013   43982   316128839
2014   47055   318857056
2015   52404   321418820
2016   63632   323127513

In [33]:
VSRR = pd.read_csv('Data/VSRR_Provisional_Drug_Overdose_Death_Counts.csv')

In [41]:
VSRR.loc[(VSRR['State'] == 'AK') & (VSRR['Year'] >= 2016)]

,State,Year,Month,Period,Indicator,Data Value,Percent Complete,Percent Pending Investigation,State Name,Footnote,Footnote Symbol,Predicted Value
144,AK,2016,April,12 month-ending,Percent with drugs specified,93.939394,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
145,AK,2016,April,12 month-ending,Number of Drug Overdose Deaths,132.000000,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,132.0
146,AK,2016,April,12 month-ending,Number of Deaths,4262.000000,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,NaN
147,AK,2016,April,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",11.000000,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,11.0
148,AK,2016,April,12 month-ending,"Opioids (T40.0-T40.4,T40.6)",95.000000,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,95.0
149,AK,2016,April,12 month-ending,"Natural, semi-synthetic, & synthetic opioids, ...",75.000000,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,75.0
150,AK,2016,April,12 month-ending,"Natural & semi-synthetic opioids, incl. methad...",68.000000,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,68.0
151,AK,2016,April,12 month-ending,Methadone (T40.3),18.000000,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,19.0
152,AK,2016,April,12 month-ending,Natural & semi-synthetic opioids (T40.2),60.000000,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,60.0
153,AK,2016,April,12 month-ending,Psychostimulants with abuse potential (T43.6),35.000000,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,36.0
154,AK,2016,April,12 month-ending,Heroin (T40.1),40.000000,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,40.0
155,AK,2016,April,12 month-ending,Cocaine (T40.5),11.000000,100,0.000000,Alaska,Numbers may differ from published reports usin...,**,11.0
156,AK,2016,August,12 month-ending,Number of Deaths,4276.000000,100,0.023386,Alaska,Numbers may differ from published reports usin...,**,NaN
157,AK,2016,August,12 month-ending,Number of Drug Overdose Deaths,138.000000,100,0.023386,Alaska,Numbers may differ from published reports usin...,**,138.0
158,AK,2016,August,12 month-ending,"Opioids (T40.0-T40.4,T40.6)",100.000000,100,0.023386,Alaska,Numbers may differ from published reports usin...,**,100.0
159,AK,2016,August,12 month-ending,"Natural, semi-synthetic, & synthetic opioids, ...",72.000000,100,0.023386,Alaska,Numbers may differ from published reports usin...,**,73.0
160,AK,2016,August,12 month-ending,Psychostimulants with abuse potential (T43.6),41.000000,100,0.023386,Alaska,Numbers may differ from published reports usin...,**,42.0
161,AK,2016,August,12 month-ending,"Natural & semi-synthetic opioids, incl. methad...",64.000000,100,0.023386,Alaska,Numbers may differ from published reports usin...,**,65.0
162,AK,2016,August,12 month-ending,Natural & semi-synthetic opioids (T40.2),55.000000,100,0.023386,Alaska,Numbers may differ from published reports usin...,**,56.0
163,AK,2016,August,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",12.000000,100,0.023386,Alaska,Numbers may differ from published reports usin...,**,13.0
164,AK,2016,August,12 month-ending,Percent with drugs specified,96.376812,100,0.023386,Alaska,Numbers may differ from published reports usin...,**,NaN
165,AK,2016,August,12 month-ending,Heroin (T40.1),39.000000,100,0.023386,Alaska,Numbers may differ from published reports usin...,**,40.0
166,AK,2016,August,12 month-ending,Methadone (T40.3),19.000000,100,0.023386,Alaska,Numbers may differ from published reports usin...,**,20.0
167,AK,2016,August,12 month-ending,Cocaine (T40.5),12.000000,100,0.023386,Alaska,Numbers may differ from published reports usin...,**,13.0
168,AK,2016,December,12 month-ending,Psychostimulants with abuse potential (T43.6),53.000000,100,0.068886,Alaska,Numbers may differ from published reports usin...,**,54.0
169,AK,2016,December,12 month-ending,Number of Deaths,4355.000000,100,0.068886,Alaska,Numbers may differ from published reports usin...,**,NaN
170,AK,2016,December,12 month-ending,"Opioids (T40.0-T40.4,T40.6)",96.000000,100,0.068886,Alaska,Numbers may differ from published reports usin...,**,97.0
171,AK,2016,December,12 month-ending,"Natural & semi-synthetic opioids, incl. methad...",53.000000,100,0.068886,Alaska,Numbers may differ from published reports usin...,**,54.0
172,AK,2016,December,12 month-ending,Heroin (T40.1),49.000000,100,0.068886,Alaska,Numbers may differ from published reports usin...,**,50.0
173,AK,2016,December,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",NaN,100,0.068886,Alaska,Numbers may differ from published reports usin...,**,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
666,AK,2019,May,12 month-ending,Number of Drug Overdose Deaths,128.000000,100,0.000000,Alaska,Underreported due to incomplete data.,*,128.0
667,AK,2019,May,12 month-ending,Percent with drugs specified,100.000000,100,0.000000,Alaska,Underreported due to incomplete data.,*,NaN
668,AK,2019,May,12 month-ending,Psychostimulants with abuse potential (T43.6),65.000000,100,0.000000,Alaska,Underreported due to incomplete data.,*,66.0
669,AK,2019,May,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",20.000000,100,0.000000,Alaska,Underreported due to incomplete data.,*,21.0
670,AK,2019,May,12 month-ending,"Natural & semi-synthetic opioids, incl. methad...",45.000000,100,0.000000,Alaska,Underreported due to incomplete data.,*,46.0
671,AK,2019,May,12 month-ending,Natural & semi-synthetic opioids (T40.2),44.000000,100,0.000000,Alaska,Underreported due to incomplete data.,*,45.0
672,AK,2019,October,12 month-ending,"Natural, semi-synthetic, & synthetic opioids, ...",63.000000,100,0.022282,Alaska,Underreported due to incomplete data.,*,64.0
673,AK,2019,October,12 month-ending,Number of Drug Overdose Deaths,146.000000,100,0.022282,Alaska,Underreported due to incomplete data.,*,146.0
674,AK,2019,October,12 month-ending,Heroin (T40.1),49.000000,100,0.022282,Alaska,Underreported due to incomplete data.,*,50.0
675,AK,2019,October,12 month-ending,Percent with drugs specified,97.260274,100,0.022282,Alaska,Underreported due to incomplete data.,*,NaN
676,AK,2019,October,12 month-ending,Methadone (T40.3),10.000000,100,0.022282,Alaska,Underreported due to incomplete data.,*,11.0
677,AK,2019,October,12 month-ending,Cocaine (T40.5),12.000000,100,0.022282,Alaska,Underreported due to incomplete data.,*,13.0
678,AK,2019,October,12 month-ending,"Opioids (T40.0-T40.4,T40.6)",92.000000,100,0.022282,Alaska,Underreported due to incomplete data.,*,93.0
679,AK,2019,October,12 month-ending,Number of Deaths,4488.000000,100,0.022282,Alaska,Underreported due to incomplete data.,*,NaN
680,AK,2019,October,12 month-ending,Natural & semi-synthetic opioids (T40.2),44.000000,100,0.022282,Alaska,Underreported due to incomplete data.,*,45.0
681,AK,2019,October,12 month-ending,"Natural & semi-synthetic opioids, incl. methad...",48.000000,100,0.022282,Alaska,Underreported due to incomplete data.,*,49.0
682,AK,2019,October,12 month-ending,Psychostimulants with abuse potential (T43.6),69.000000,100,0.022282,Alaska,Underreported due to incomplete data.,*,70.0
683,AK,2019,October,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",27.000000,100,0.022282,Alaska,Underreported due to incomplete data.,*,28.0
684,AK,2019,September,12 month-ending,Number of Drug Overdose Deaths,136.000000,100,0.022326,Alaska,Underreported due to incomplete data.,*,136.0
685,AK,2019,September,12 month-ending,"Natural, semi-synthetic, & synthetic opioids, ...",55.000000,100,0.022326,Alaska,Underreported due to incomplete data.,*,56.0
686,AK,2019,September,12 month-ending,"Opioids (T40.0-T40.4,T40.6)",84.000000,100,0.022326,Alaska,Underreported due to incomplete data.,*,85.0
687,AK,2019,September,12 month-ending,Percent with drugs specified,97.794118,100,0.022326,Alaska,Underreported due to incomplete data.,*,NaN
688,AK,2019,September,12 month-ending,Psychostimulants with abuse potential (T43.6),64.000000,100,0.022326,Alaska,Underreported due to incomplete data.,*,65.0
689,AK,2019,September,12 month-ending,Natural & semi-synthetic opioids (T40.2),40.000000,100,0.022326,Alaska,Underreported due to incomplete data.,*,41.0
690,AK,2019,September,12 month-ending,Cocaine (T40.5),12.000000,100,0.022326,Alaska,Underreported due to incomplete data.,*,13.0
691,AK,2019,September,12 month-ending,"Natural & semi-synthetic opioids, incl. methad...",43.000000,100,0.022326,Alaska,Underreported due to incomplete data.,*,44.0
692,AK,2019,September,12 month-ending,Number of Deaths,4479.000000,100,0.022326,Alaska,Underreported due to incomplete data.,*,NaN
693,AK,2019,September,12 month-ending,Heroin (T40.1),44.000000,100,0.022326,Alaska,Underreported due to incomplete data.,*,44.0
694,AK,2019,September,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",24.000000,100,0.022326,Alaska,Underreported due to incomplete data.,*,25.0
695,AK,2019,September,12 month-ending,Methadone (T40.3),NaN,100,0.022326,Alaska,Underreported due to incomplete data. Data su...,*,NaN